env:
  node: true
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
  - "simple-import-sort"
  - "prettier"
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "next/core-web-vitals"
  - "prettier"
rules: {
  "simple-import-sort/exports": "error",
  "simple-import-sort/imports": "error",
  "@typescript-eslint/no-unused-vars": ["error", { "args": "none", "destructuredArrayIgnorePattern": "^_" }],
  "prettier/prettier": "error",
}
