# This workflow deploys our app

name: Deploy

# Controls when the action will run
on:
  pull_request:
    branches:
      - '*'

jobs:
  deploy_dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 15.x

      - name: install dependencies
        run: yarn install

      - name: test
        run: yarn test

      - name: deploy dev
        run: yarn run vercel --prod --token ${{secrets.VERCEL_TOKEN}}
        env:
          VERCEL_ORG_ID: ${{secrets.VERCEL_ORG_ID}}
          VERCEL_PROJECT_ID: ${{secrets.VERCEL_PROJECT_ID}}

  deploy_prod:
    needs: deploy_dev
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 15.x

      - name: install dependencies
        run: yarn install

      - name: test
        run: yarn test

      - name: deploy prod
        run: yarn run vercel --prod --token ${{secrets.VERCEL_TOKEN}}
        env:
          VERCEL_ORG_ID: ${{secrets.VERCEL_ORG_ID}}
          VERCEL_PROJECT_ID: ${{secrets.VERCEL_PROJECT_ID}}
